[project]
name = "videolingo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autocorrect-py>=2.14.0",
    "demucs",
    "edge-tts>=7.0.2",
    "g2p-en>=2.1.0",
    "json-repair>=0.47.8",
    "librosa>=0.11.0",
    "numpy<2.0",
    "openai>=1.97.1",
    "opencv-python>=4.11.0.86",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pip>=25.1.1",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "pypinyin>=0.55.0",
    "rich>=14.0.0",
    "ruamel-yaml>=0.18.14",
    "soundfile>=0.13.1",
    "spacy>=3.8.7",
    "syllables>=1.1.1",
    "torch>=2.0.0,<3.0.0",
    "torchaudio>=2.0.0,<3.0.0",
    "webrtcvad>=2.0.10",
    "whisperx>=3.2.0",
    "yt-dlp>=2025.7.21",
]

[tool.uv.sources]
demucs = { git = "https://github.com/adefossez/demucs" }
